const seats: Record<string, string> = {
"kevin luong":"Head Table",
"bonnie cheung":"Head Table",
"amy cheung":"Head Table",
"maria kang":"Head Table",
"agnes lei":"Head Table",
"gabrielle kim":"Head Table",
"jonathan ng":"Head Table",
"chris zhang":"Head Table",
"stephanie wong":"Head Table",
"dustin zhang":"Head Table",
"jordan luong":"Head Table",
"ethan liang":"Head Table",
"huy luong": "Table 4",
"auntie khoánh": "Table 4",
"uncle nghĩa": "Table 4",
"uncle xương": "Table 4",
"uncle michael": "Table 4",
"auntie lanchi": "Table 4",
"grandma": "Table 4",
"lan duong": "Table 4",
"william ly": "Table 2",
"cherrie chan": "Table 2",
"lily cao": "Table 2",
"sophia ly": "Table 2",
"victoria ly": "Table 2",
"philip ly": "Table 2",
"selena liu": "Table 2",
"michael ly": "Table 2",
"wong ji ling": "Table 2",
"letien bhaskar": "Table 3",
"sanjay bhaskar": "Table 3",
"andi duong": "Table 3",
"timothy duong": "Table 3",
"dylan duong": "Table 3",
"enric duong": "Table 3",
"bill duong": "Table 3",
"cindy duong": "Table 3",
"kim anh duong": "Table 1",
"michael marrone": "Table 1",
"james duong": "Table 1",
"abby andal": "Table 1",
"tam duong": "Table 1",
"khang duong": "Table 1",
"kayla quinlan": "Table 1",
"teffran chan": "Table 8",
"jashanjot singh sohanpal": "Table 8",
"lucy shen": "Table 8",
"francis peng": "Table 8",
"stephen peng": "Table 8",
"jason wang": "Table 8",
"alexa cheung": "Table 8",
"david yang": "Table 8",
"luke xu": "Table 8",
"benjamin lo": "Table 6",
"jocelyn chan": "Table 6",
"charina alducente": "Table 6",
"joshua sayavong": "Table 6",
"sherman xiong": "Table 6",
"tom sun": "Table 6",
"arjun bali": "Table 6",
"wendy soung chen": "Table 6",
"anthea lai": "Table 7",
"daniel pang": "Table 7",
"vincent dao": "Table 7",
"erika lee": "Table 7",
"natalie chan": "Table 7",
"sean siow": "Table 7",
"tania ng": "Table 7",
"jacqueline yeung": "Table 7",
"wing chan": "Table 5",
"megan chan": "Table 5",
"alex chung": "Table 5",
"agnes yuen": "Table 5",
"john yuen": "Table 5",
"peter cheung": "Table 5",
"dora cheung": "Table 5",
"sarina chan": "Table 5",
"uncle giai": "Table 9",
"auntie cathy": "Table 9",
"uncle quang": "Table 9",
"auntie lệ": "Table 9",
"irene luong": "Table 9",
"vivian luong": "Table 9",
"nathan chan": "Table 9",
"amy luong": "Table 9",
"peter lu": "Table 9",
"uncle sinh": "Table 10",
"auntie claudine": "Table 10",
"auntie thủy": "Table 10",
"uncle thiện": "Table 10",
"uncle tuấn": "Table 10",
"uncle từ": "Table 10",
"auntie tuyết": "Table 10",
"uncle trường": "Table 11",
"auntie tâm": "Table 11",
"auntie lam": "Table 11",
"uncle khâm": "Table 11",
"auntie mai": "Table 11",
"bà năm": "Table 11",
"uncle hùng": "Table 11",
"christina chan": "Table 12",
"paul suk": "Table 12",
"lindsay lew": "Table 12",
"owen perrett": "Table 12",
"bernice chow": "Table 12",
"david tasker": "Table 12",
"alicia sheng": "Table 12",
"gavin sum": "Table 12",
"derin denizkusu": "Table 13",
"joy zhang": "Table 13",
"heejae park": "Table 13",
"perry ha": "Table 13",
"sukiena abdullah": "Table 13",
"volo kluev": "Table 13",
"lynnea tan": "Table 13",
"emily lam": "Table 13",
"ivan zhang": "Table 14",
"charley huang": "Table 14",
"adrien morisot": "Table 14",
"ashley ma": "Table 14",
"jessica wu": "Table 14",
"norman spencer": "Table 14",
"katarina guillen": "Table 14",
"jane fu": "Table 14",
"kalie ho": "Table 18",
"ashley sun": "Table 18",
"vivian kwok": "Table 18",
"christine d-carlos": "Table 18",
"nardin kirolos": "Table 18",
"chantal lim": "Table 18",
"nathan leung": "Table 17",
"michael ru": "Table 17",
"julia lee": "Table 17",
"yifan wu": "Table 17",
"yemin shou": "Table 17",
"kelly kong": "Table 17",
"junhao dong": "Table 17",
"timothy keung": "Table 16",
"gaisley chong": "Table 16",
"cecilia chong": "Table 16",
"ivan yeung": "Table 16",
"elim yeung": "Table 16",
"andes lo": "Table 16",
"gwen lo": "Table 16",
"stella keung": "Table 16",
"felix fan": "Table 15",
"simon cheng": "Table 15",
"pauline cheng": "Table 15",
"helium tsui": "Table 15",
"kitty tsui": "Table 15",
"karen wong": "Table 15",
"candy pan": "Table 15",
"melissa chen": "Table 15",
"alvin poon": "Table 19",
"denzel kwan": "Table 19",
"arthur lam": "Table 19",
"jeremy hidajat": "Table 19",
"selena uong": "Table 19",
"katerina li": "Table 19",
"vanessa yuan": "Table 19",
"michelle au yeung": "Table 19",
"evelyn welch": "Table 20",
"jeffrey zhou": "Table 20",
"anna dong": "Table 20",
"bill chen": "Table 20",
"matthew sem": "Table 20",
"anna huang": "Table 20",
"kevin lin": "Table 20",
"bailey wei": "Table 20",
"flora ng": "Table 22",
"jessie ho": "Table 22",
"florence wong": "Table 22",
"anders li": "Table 22",
"lawrence lam": "Table 22",
"anita lam": "Table 22",
"rosalie lau": "Table 22",
"raymond siu": "Table 22",
"millin gabani": "Table 21",
"salman jalal": "Table 21",
"roxanna dordari": "Table 21",
"christian johnson": "Table 21",
"johnathan van gorp": "Table 21",
"mitchell catoen": "Table 21",
"alessa dalcourt": "Table 21",
"rares gosman": "Table 21",
"rosanna le": "Table 23",
"marissa ho": "Table 23",
"chris barnard": "Table 23",
"grace ng": "Table 23",
"rozyl gatchalon": "Table 23",
"raymond tran": "Table 23"
};

export default seats;
